### PR TITLE
Duplicated class files in jar

### LINKED ISSUE #301: Duplicate kotlin_module with kotlin 1.8.20
I don't know whether this issue with kotlin or atomicfu but guessed to report here.

My code uses atomicfu 0.20.2 and builds wth kotlin 1.8.10 but if I try to update to kotlin 1.8.20 the build fails:

```
Execution failed for task ':jar'.
> Entry META-INF/project.kotlin_module is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

Somehow I figured that this is related to atomicfu. If it is removed from dependencies (and the code corrected to be compilable) then the build finishes successfully.

### PR DESCRIPTION
**Pull request by mvicsokolova**
After update from Gradle 6.8 to 7.3 the problem with building jvm-only projects was found: jar task is failing with this error
```
Execution failed for task ':jar'.
> Entry IntArithmetic.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

Reproduced with Kotlin 1.8.20+

Jar task tries to pack both original and transformed class files.

Fixes #301, #295

### CODE REVIEW

File: atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt [hunk 1]
```diff
@@ -254,50 +245,73 @@ private fun Project.configureTransformationForTarget(target: KotlinTarget) {
...
             val mainCompilation =
                 compilation.target.compilations.getByName(KotlinCompilation.MAIN_COMPILATION_NAME)
-            val originalMainClassesDirs = project.files(
-                // use Callable because there is no guarantee that main is configured before test
-                Callable { originalDirsByCompilation[mainCompilation]!! }
+            val originalMainClassesDirs = project.objects.fileCollection().from(
+                mainCompilation.compileTaskProvider.flatMap { (it as KotlinCompileTool).destinationDirectory }
             )
 
             // KGP >= 1.7.0 has breaking changes in task hierarchy:
```
Comment (Tapchicoma) [inline atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt:317]: I would propose to remove this if here as now minimal supported KGP version is `1.7.0`

**Review by Tapchicoma — APPROVED** [review]
